bank controller and service
djordjeMalkier/Praksa pull request #25
Opened 2022-11-25 14:11 UTC by kyuubi98

2022-11-28 08:27 UTC, daviddimic commented on src/main/java/common/bankarskiSistem/controller/BankController.java
> +            bank = bankService.findById(idBank);
Treba `findByIdBank`

2022-11-28 08:49 UTC, daviddimic commented on src/main/java/common/bankarskiSistem/model/Bank.java
> +    @ManyToOne(cascade = CascadeType.MERGE)
ManyToOne ne bi trebalo da ima cascade. Samo sa strane oneToMany

2022-11-29 12:07 UTC, daviddimic commented on src/main/java/common/bankarskiSistem/controller/dto/ConversionMapper.java
> +    @Mapping(source = "idConversion", target = "idConversion")
Ako je isto ime u mapping, onda ne mora da se navodi

2022-11-29 12:09 UTC, daviddimic requested changes
Izbrisati zakomentarisan kod, i ispraviti  Mapping

2022-11-29 12:22 UTC, daviddimic approved these changes

2022-11-29 12:22 UTC, jovanazivkovic99 approved these changes

2022-11-29 12:34 UTC, jovanazivkovic99 commented on src/main/java/common/bankarskiSistem/service/BankService.java
> +        bankRepository.save(updatedBank);
Mozda da umesto ove dve metode updateBankName i updateBankAddress, da bude jedna update metoda u servisu npr updateBank, i onda posle moze da se pravi koliko god endpointa u kontroleru

2022-11-29 12:34 UTC, jovanazivkovic99 requested changes
Jedna metoda za update umesto vise

2022-11-29 12:38 UTC, tamirzad commented on src/main/java/common/bankarskiSistem/model/Bank.java
> +    @ManyToOne(cascade = CascadeType.MERGE)
👍

2022-11-29 13:58 UTC, jovanazivkovic99 approved these changes

2022-11-29 13:58 UTC, merged